project_name: terraform-workspace-manager

env_files:
  github_token: ${{ secrets.access_token }}

release:
  github:
    owner: TomTucka
    name: terraform-workspace-manager

builds:
  - binary: terraform-workspace-manager
    id: terraform-workspace-manager
    main: ./main.go
    goos:
      - freebsd
      - openbsd
      - solaris
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
